name: Build C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Set up Visual Studio
      uses: microsoft/setup-vs@v1
      with:
        vs-version: 2022

    - name: Install dependencies (optional)
      run: |
        if exist vcpkg.json (
          .\vcpkg\vcpkg.exe install
        )

    - name: Build the solution
      run: |
        msbuild.exe SqaureConfig.sln /p:Configuration=Release /m
